### ISSUE TITLE
Not able to use GPU in basic retrieval training

### ISSUE THREAD

**Issue by buntys2010** [tensorflow/recommenders#474]
I am trying to use documentation to build basic retrieval system (https://www.tensorflow.org/recommenders/examples/basic_retrieval) with my own database (Similar code as here https://github.com/petrov826/tfrs/blob/main/create_dataset_in_tfrs.ipynb ).

During training its using only CPU and not using any GPU although GPU is available.

My code is available [here ](https://www.kaggle.com/buntyshah/fork-of-sony-final-model)(Its taking 30 mins to run 1 epoch) , please let me know if i am doing something wrong here?

**Comment by patrickorlando** [comment]
Computing the evaluation metrics during training slows down the training speed a lot. 
As mentioned in https://github.com/tensorflow/recommenders/issues/178, try disabling eval metrics during training and see if that fixes your issue.

**Comment by buntys2010** [comment]
#178 resolved my issue.
